PyThaiNLP/pythainlp

pythainlp/romanization/pyicu.py, pythainlp/tokenize/pyicu.py
Almost as title says, would be required 'import sys' before 'import icu'
=> Fix "NameError: name 'sys' is not defined" when icu was not installed

pythainlp/__init__.py, pythainlp/tokenize/__init__.py, pythainlp/tokenize/longest.py, pythainlp/tokenize/mm.py, pythainlp/tokenize/newmm.py, pythainlp/tokenize/wordcutpy.py
สวัสดีครับน้องต้นตาล
ผมปรับจุดที่แก้ไขได้ให้นิดหน่อยและช่วย improve ตรงส่วนของการตัดคำโดยใช้ custom dict ให้นิดหน่อยน่ะครับ 
สิ่งที่แก้ไข:
1. แก้ไขเลข version 1.5 -> 1.6
2. ลบ `f.close()` ออกไป เพราะหากใช้ open แล้ว f จะปิดเองอัตโนมัต หลังออกจาก with statement
3. พอดี code เก่ามันช้าตรงที่ ทุกครั้งที่เรียก dict_word_tokenize() แล้วมันเอา read file หรือ/และ เอา list of words ไปสร้าง trie ทุกครั้ง ซึ่งจริงๆแล้วมันไม่ได้จำเป็นและทำให้ช้ามากกว่าเรียกใช้ default dict หลายสิบเท่าเลย 
ผมก็เลยแก้ไขไฟล์ __init__.py ใน folder tokenize โดยเพิ่ม class Tokenizer ขึ้นมา ซึ่ง user จะ initiate object นี้แค่ครั้งเดียว พร้อมส่ง custom dict หรือใหม่ก็ได้ จากนั้นก็เรียกใช้ word_tokenize() ไปตัดคำได้เลย ตอนนี้ผมทำแค่ newmm ก่อน เพราะผมไม่กล้าแก้ code เก่ามากเกินไป เพราะมันค่อนข้างเปลี่ยน behevior ของตัว …
=> Improved custom dict tokenization

pythainlp/corpus/__init__.py, pythainlp/tools/__init__.py, pythainlp/word_vector/thai2vec.py, requirements-travis.txt, requirements.txt, setup.py
อัพเดตไฟล์ corpus หรือ model ใน pythainlp-data โดยที่ไม่ต้องอัพเวชั่น PyThaiNLP ใหม่
=> update corpus for pythainlp-data

pythainlp/romanization/royin.py
Fixed a bug in romanization for 'ฤ' as per [issue#86](https://github.com/PyThaiNLP/pythainlp/issues/86).
I followed [CU-Arts Thai Romanization guideline](http://www.arts.chula.ac.th/~ling/tts/principles_eng.pdf)  and [this resource](http://mcpswis.mcp.ac.th/html_edu/cgi-bin/mcp/main_php/print_informed.php?id_count_inform=12405). I also include 3 test cases in _royin.py_ as follows:
1. กฤษฎา
2. ฤกษ์
3. ฤดูกาล
However, I can't find strict rules/regular patterns on how 'ฤ' should be pronounced as individual vowel, for example, 'ฤดู', and 'ฤทธิ์'. So I treat both cases as the same pronunciation.
I also correct _royin.py_ coding style to complie with PEP8.
=> Fixed rare vowel bug and change style according to PEP8

pythainlp/tokenize/__init__.py, pythainlp/tokenize/newmm.py, pythainlp/tokenize/tcc.py
- move common TCC function (tcc_pos) from newmm.py to tcc.py
- sent_tokenize() and subword_tokenize() must return something
- replace while loops with for loops in isthai() and syllable_tokenize() (faster)
- more meaningful exception error message, now report the unknown engine name
=> Refactor tokenize code

.gitignore
Ignore files like .ipynb_checkpoints, .DS_Store, and .Spotlight*
=> .gitignore to ignore Jupyter notebook checkpoints and macOS generated files

CONTRIBUTING.md, pythainlp/summarize/__init__.py
- add __ prefix for private class members
- summarize_text() will always return something (if summarization engine not found, return first n sentences)
- summarize_text() documentation
=> summarize: Small variable rename and handle engine not found case

pythainlp/corpus/__init__.py, pythainlp/tools/__init__.py, pythainlp/ulmfit/__init__.py, pythainlp/ulmfit/utils.py
- put corpus database url into CORPUS_DB_URL constant 
- sort imports, remove unused imports
- add __ prefix for private class members
- precompile patterns at initialization (ThaiTokenizer class)
- use "not" for condition comparison (in a reasonable situation) with booleans (as suggested by PEP8)
- make indent more consistent
=> Clean code (/corpus, /tools, /ulmfit)

examples/romanization.py, pythainlp/__init__.py, pythainlp/chunk/__init__.py, pythainlp/collation/__init__.py, pythainlp/romanization/__init__.py, pythainlp/romanization/pyicu.py, pythainlp/romanization/royin.py, pythainlp/romanization/thai2rom.py, pythainlp/sentiment/__init__.py, pythainlp/sentiment/ulmfit_sent.py, pythainlp/spell/__init__.py, pythainlp/spell/hunspell.py, pythainlp/spell/pn.py, pythainlp/tag/__init__.py, pythainlp/tag/old.py, pythainlp/tag/perceptron.py, pythainlp/ulmfit/utils.py, pythainlp/util/__init__.py, pythainlp/word_vector/thai2vec.py, tests/__init__.py
- precompile regexes
- more description for each file (at the beginning)
- naming convention: rename thai2rom -> ThaiTransliterator [CamelCase for Class], romanization() -> romanize() [function name should be a verb]
- update examples and tests to new names
- add __ prefix for private members (ThaiTransliterator)
- make sure a function will always return something -- if no engine found, use default (romanize(), sentiment(), spell(), pos_tag())
- sort imports, remove unused imports
- make consistent indentation (replace tabs with spaces, make it 4-space indent)
- remove Python 2 condition checks
=> Code cleaning + small optimization

README-pypi.md, README.md, pythainlp/corpus/ttc.py, pythainlp/number/thainum.py, pythainlp/number/wordtonum.py, pythainlp/sentiment/__init__.py, pythainlp/ulmfit/utils.py, tests/__init__.py
- TTC should read ttc_freq.txt (was tnc_freq.txt)
- test case for bahttext for full number without satang
- test case for pythainlp.corpus.remove
- update readme
=> Minor bug fixes + add test cases + update readme

pythainlp/number/__init__.py, pythainlp/number/digitconv.py, pythainlp/number/numtoword.py, pythainlp/number/wordtonum.py, tests/__init__.py
- separated functions to smaller files
- add more test cases
=> Number converters: convert more than one digit at a time

.travis.yml, CONTRIBUTING.md, README-pypi.md, README.md, appveyor.yml, pythainlp/number/wordtonum.py, pythainlp/sentiment/ulmfit_sent.py, pythainlp/tag/__init__.py, pythainlp/tag/perceptron.py, pythainlp/tag/unigram.py, pythainlp/tokenize/__init__.py, pythainlp/tokenize/deepcut.py, pythainlp/tokenize/etcc.py, pythainlp/tokenize/longest.py, pythainlp/tokenize/multi_cut.py, pythainlp/tokenize/newmm.py, pythainlp/tokenize/pyicu.py, pythainlp/tokenize/tcc.py, pythainlp/transliterate/__init__.py, pythainlp/transliterate/royin.py, pythainlp/word_vector/thai2vec.py, setup.py, tests/__init__.py
- more test cases for POS taggers, spell checkers, thai2vec, tokenizers, transliterators, and Wordnet
- handle None and empty input cases
=> More test cases - reached 80% coverage

docs/pythainlp-dev-thai.md, pythainlp/__init__.py, pythainlp/tokenize/etcc.py
- rename from ```thai_alphabets``` to ```thai_consonants``` to be more accurate
- add more description about Thai consonants, letters, and characters 
- minor adjustment with no logic change
=> more description about Thai consonants, letters, characters

pythainlp/tokenize/__init__.py, pythainlp/tokenize/etcc.py, pythainlp/tokenize/tcc.py
* Fix TCC reference
* Add ETCC reference
* Include  ETCC in subword_tokenize module
=> Subword tokeniser documentation improvement

README-pypi.md, README.md, notebooks/pythainlp-get-started.ipynb, pythainlp/__init__.py, pythainlp/soundex/__init__.py, pythainlp/spell/__init__.py, pythainlp/summarize/__init__.py, pythainlp/summarize/freq.py, pythainlp/tokenize/__init__.py, pythainlp/tokenize/pyicu.py, pythainlp/transliterate/__init__.py, pythainlp/transliterate/ipa.py, pythainlp/transliterate/pyicu.py, pythainlp/transliterate/royin.py, pythainlp/transliterate/thai2rom.py, pythainlp/ulmfit/__init__.py, tests/__init__.py
- royin.romanize can now romanize untokenized text
- Add more info about the Royal Thai General System of Transcription (RTGS)
- ICU transliterate engine "pyicu" renamed to just "icu"
- Show ICU transliteration example in Get Started notebook
=> Improvement in romanization

pythainlp/corpus/tnc.py, pythainlp/tokenize/__init__.py, tests/__init__.py
- reorder condition checks in `pythainlp.tokenize.dict_trie` so it catch Trie before Iterable
- more test cases for dict_trie and soundex
=> Reorder if checks for dict_trie and more test cases

appveyor.yml, pythainlp/corpus/__init__.py, pythainlp/corpus/tnc.py, pythainlp/spell/pn.py, tests/__init__.py
- fix/add return type hinting for functions in pythainlp.corpus
- fix deprecated inline flag for regular expression in TNC
- add more test cases for thai_strftime()
- add test for Python 3.7 (appveyor) + update PyICU to 2.3.1
=> Fix various small issues

pythainlp/tokenize/__init__.py, pythainlp/ulmfit/__init__.py, pythainlp/word_vector/__init__.py, tests/__init__.py
"ulmfit" engine option is supposed to be used internally.
Remove to avoid confusion.
See #222 for more discussion.
=> Remove "ulmfit" engine option in word_tokenize()

.travis.yml, bin/pythainlp, pythainlp/__init__.py, pythainlp/tag/__init__.py, pythainlp/tag/named_entity.py, setup.py
- fixed #230 
- new train ThaiNER
=> PyThaiNLP 2.0.6

pythainlp/tools/__init__.py
Instead of hard-coding `PYTHAINLP_DATA_DIR`, this allows one to change the dir with an environmental variable.
=> add option of setting data dir with an enviromental variable

pythainlp/tag/named_entity.py, tests/test_tag.py
Add output like html tag (ThaiNameTagger).
```python
>>> from pythainlp.tag.named_entity import ThaiNameTagger
>>> ner = ThaiNameTagger()
>>> ner.get_ner("วันที่ 15 ก.ย. 61 ทดสอบระบบเวลา 14:49 น.",tag=True)
'วันที่ <DATE>15 ก.ย. 61</DATE> ทดสอบระบบเวลา <TIME>14:49 น.</TIME>'
```
=> NER : Add output like html tag

bin/pythainlp, pythainlp/cli/__init__.py, pythainlp/cli/corpus.py, pythainlp/cli/soundex.py, pythainlp/cli/tagging.py, pythainlp/cli/tokenization.py
related to #250 
Example usages:
```
$ ./bin/pythainlp --help
usage: pythainlp [-h] command
positional arguments:
command     [corpus|tokenization|soundex]
optional arguments:
-h, --help  show this help message and exit
$  ./bin/pythainlp tokenization word  --text "ผมร<0e31>กประเทศไทย? สามารถ" --engine newmm
Using engine=newmm
ผม|รัก|ประเทศไทย|?| |สามารถ
$ ./bin/pythainlp tokenization syllable  --text "ผมร<0e31>กประเทศไทย? สามารถ"
Using engine=ssg
ผม~รัก~ประ~เทศ~ไทย~? ~สา~มารถ
$ ./bin/pythainlp soundex  --text "บ<0e39>รณการ" --engine lk82
บE419
```
=> Better CLI

appveyor.docs.yml, docs/clean_directory.sh, docs/conf.py
Add new feature to automatically build Sphinx documentation and upload to thainlp.org/pythainlp/docs/<branch_name>
Any commits in  `dev` or `2.x` with the commit message that contains `(build and deploy docs)` will trigger the Appveyor CI server (project id: [pythainlp-wdor1](https://ci.appveyor.com/project/wannaphongcom/pythainlp-wdor1))  to
1) Build the Sphinx documentation with `make html`
2) Save generated files as build artifacts (https://ci.appveyor.com/project/wannaphongcom/pythainlp-wdor1/build/artifacts)
3) Upload generated files to the thainlp.org (thainlp.org/pythainlp/docs/<base_branch_name>) via FTP
=> Automatically build/deploy documentation

docs/notes/installation.rst, pythainlp/tokenize/__init__.py, pythainlp/tokenize/deepcut.py, pythainlp/tokenize/longest.py, pythainlp/tokenize/multi_cut.py, pythainlp/tokenize/newmm.py, pythainlp/tokenize/trie.py, requirements.txt
Regarding @korakot 's comment to replace `marisa-trie`, this PR proposes an implementation of the Trie data structure written in Python.
Google Colab: https://colab.research.google.com/drive/1mzITCObabCdQvEV7d_YpHpiABGRpqNhW#scrollTo=fg9TvqZvbHPs
=> Change from `marisa-trie` to a Trie implementation written in python

pythainlp/tools/__init__.py
To my understanding, PyThaiNLP will always create a new data directory if it does not yet exist. In the original code, the non-existence of the data directory is check before the creation of the directory is attempted. Although this might work fine in single-processing environment, but it will fail arbitrarily if this code is deployed under multi-processing environment. That is, it is possible that two processes reach line 51 (of the original code) around the same time (passing the if-check), but one of the processes will fail before the other will create the same directory before it. This is called **racing condition**.
This patch will solve such issue by simply use `exist_ok=True` flag to ignore errors when the directory already exists.
Please review.
=> Remove racing condition in making pythainlp data directory

pythainlp/util/digitconv.py, pythainlp/util/keyboard.py
The modified source file involves code which convert texts back and forth between English-US QWERTY layout and Thai Kedmanee layout. 
Two main changes are introduced:
1. Instead of manually applying mapping to each character, `str.maketrans` and `str.translate` are deployed. The behavior of functions `eng_to_thai` and `thai_to_eng` do not change whatsoever, but this new approach should yield a slightly better code performance.
2. Docstrings are modified to clarify that the conversion happens between two specific keyboard layouts, not between two languages. I guess we can create an issue to discuss and resolve this.
Similar to 1. above (for better performance).
=> Optimize keyboard layout switching translation code & digits translation

pythainlp/spell/__init__.py, pythainlp/spell/pn.py, tests/test_spell.py
Three main improvements:
1. Fixed some mismatched type annotations in the original code
2. Corrected the spelling, ironically, of some words in this subpackage. (I also took some liberty of modifying some docstrings to make it clearer.)
3. Rewrote some lines of Python code that could obviously be improved or corrected.
Please review.
=> pythainlp.spell: Fix type annotations, docstring spellings, etc.

pythainlp/spell/pn.py, tests/test_spell.py
I've added the try-catch block for checking the numeric type before calling spell method.
if not word:
return ""
try:
if "." in word:
float(word)
else:
int(word)
return word
except ValueError:
pass
return self.spell(word)[0]
=> Fix "ใน" correction when pass numeric type into correct function in spell module

docs/notes/installation.rst, pythainlp/tools/__init__.py
It would be great to document the behavior of the `PYTHAINLP_DATA_DIR` environment variable (which lies deep in the code). This will enable users of this library to discover that they may configure the location from `~/pythainlp-data` to whatever they wish (should also be useful in the context of application containerization, such as with Docker).
This pull requests makes two changes, each at the following locations:
1. In the docstring of the function `get_pythainalp_data_path` in `pythainlp.tools`;
2. In the installation page of the Sphinx doc.
=> Added docs on PYTHAINLP_DATA_DIR environ variable

docs/api/corpus.rst, pythainlp/corpus/tnc.py, tests/test_corpus.py
Remove pythainlp.corpus.tnc.word_freq
=> Remove pythainlp.corpus.tnc.word_freq

pythainlp/corpus/__init__.py, pythainlp/tokenize/attacut.py, pythainlp/tokenize/deepcut.py, pythainlp/tokenize/ssg.py, tests/test_corpus.py, tests/test_tokenize.py, tests/test_util.py
- More test cases for corpus functions
- More test cases for `thai_time()`
- More "semantic" tests for tokenizers
- Test if deprecated function raises DeprecationWarning (commented out for now, as there is a bug in unittest assertWarns, a PR is in the process at https://github.com/python/cpython/pull/4800)
=> More unit tests

README.md, pythainlp/corpus/__init__.py, pythainlp/tokenize/__init__.py, pythainlp/tokenize/newmm.py, pythainlp/util/thai_time.py, pythainlp/word_vector/__init__.py, setup.py, tests/test_tokenize.py, tests/test_util.py, tox.ini
Description https://github.com/PyThaiNLP/pythainlp/releases/tag/2.1.dev8
=> PyThaiNLP 2.1dev8
